

services:
  web:
    build:
      context: src/app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - broker
  
  scooter:
    build:
      context: src/scooter
      dockerfile: Dockerfile
    depends_on:
      - broker
  server:
    build:
      context: src/server
      dockerfile: Dockerfile
    depends_on:
      - broker

  broker:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
