

services:
  web:
    build:
      context: src/app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src/app:/app
      
  broker:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1884:1883"
      - "9002:9001"
    volumes:
      - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
