@startuml
node "Sensors" as device #PHYSICAL {
}

node "Gateway 'KBox A-201 mini'" as gateway #PHYSICAL {
  component "Iot Gateway" as iot_gateway #APPLICATION
  node "SSD" as memory #TECHNOLOGY
  component "TPM" as tpm #APPLICATION
}


cloud "Virtual Private Cloud" as cloud #LightBlue {
  node "Server" as server #PHYSICAL {
    component "Abbaco Contros data mining" as data_mining #APPLICATION
    component "analytics software" as analytics #APPLICATION
  }
}

node "Customer PC" as pc #PHYSICAL {}

device "N" -UP-> "1" gateway: TCP (through LTE and GSM or Wifi)
gateway "*" -UP-> "1" server: TCP/IP
pc "*" --> "1" server: HTTPS

@enduml
