@startuml

[*] --> User
PaymentProcessing --> Server : Process Payment
Server --> PaymentProcessing : Ack or Deny

Server --> Scooter : Lock and Detect Parking
Scooter --> Server : Report Scooter Status

User --> Server : Request Scooter
Server --> User : Return Details or Return Error

User --> Server : End Parking
Server --> User : Parking Confirmed or Reposition Scooter

Server --> Server : Validate Parking




@enduml
