@startuml
[*] --> Idle

Admin: request_info()
User: request_info()
Idle --> c : evt_login

state c <<choice>>
c --> Admin : is_admin() == True
c --> User : is_user() == True
c --> Idle : else

Admin --> Idle : evt_logout
User --> Idle : evt_logout

User --> c2 : evt_ack_open_request

state c2 <<choice>>
c2 --> Idle : payment_accepted() == False
c2 --> ScooterRunning : payment_accepted() == True

ScooterRunning : entry / send_evt_unlock()
ScooterRunning : exit / send_evt_lock()

ScooterRunning --> Idle : evt_ack_close_request
@enduml