@startuml
[*] --> Locked

Locked : entry / close_scooter()
Running : entry / open_scooter()
Maintenance : entry / deactivate_scooter()

Locked --> Locked : evt_request_info
Locked --> Maintenance : evt_deactivate
Maintenance --> Locked : evt_activate
Locked --> Running : evt_unlock

state c <<choice>>
Running --> c : evt_park_scooter
c --> Locked : is_parking_valid() == True
c --> Running : is_parking_valid() == False

@enduml